### ISSUE TITLE
Test Failure UI Screenshots

### ISSUE THREAD

**Issue by mgibbs1259** [gigantum/gigantum-testing#26]
**Is your feature request related to a problem? Please describe.**
When a test fails, obtain a screenshot of the UI

**Describe the solution you'd like**
Use something like ```driver.save_screenshot("screenshot.png")``` to save a screenshot when a test fails that will end up in an S3 bucket

**Exit criteria**
Taking a screenshot of the UI when the test fails will aid in pinpointing and fixing issues

**Comment by billvb** [comment]
closed via PR
