### ISSUE TITLE
Create a playbook to link dataset to a project

### ISSUE THREAD

**Issue by mengjiez99** [gigantum/gigantum-testing#27]
**Is your feature request related to a problem? Please describe.**
We currently have playbooks for create/publish dataset and project separately, it would be nice to test linking dataset to project and publish project with dataset linked. Also we need to test linking dataset to a published project and syncing the project. 

**Describe the solution you'd like**
Order 1: link and then publish
1. Create a dataset
2. Create a project
3. Link the dataset to the project and publish

Order 2: publish and then link and sync. 
1. Create a dataset-2
2. Create a project-2
5. Link the dataset to the project and sync. 

**Exit criteria**
Should be able to link dataset and publish/sync project successfully.

**Comment by billvb** [comment]
closed via PR
