### ISSUE TITLE
Test for importing all public featured projects

### ISSUE THREAD

**Issue by billvb** [gigantum/gigantum-testing#6]
**Describe the solution you'd like**
We should have a playbook just like build all base images that imports all the featured public projects that are featured on the gigantum website. This will serve as a test that our projects are reproducible and that the import functionality works.

**Exit criteria**
Pick the top-3 public projects and have a playbook that imports each of them, and confirms that they all build successfully.

**Comment by mgibbs1259** [comment]
We can close this issue.
