### ISSUE TITLE
Simple playbook for publishing and syncing

### ISSUE THREAD

**Issue by billvb** [gigantum/gigantum-testing#7]
**Is your feature request related to a problem? Please describe.**
We need a very simple regression test for publishing projects. The playbook should involve simply creating a new project and publishing.

**Describe the solution you'd like**
A simple test or two to publish a trivial project. It should confirm that the publish is successful. This can be double checked by using some Git commands to make sure the remote was created properly. In order to avoid clutter, we should publish these privately, and be sure to clean up.

**Exit criteria**
* Ensure that project on remote server actually exists
* Ensure UI indicates that publish succeeded.
* Ensure changes can be made and synced.

**Comment by mgibbs1259** [comment]
We can close this issue.
